// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
public partial class MLIrisFlower
{
    /// <summary>
    /// model input class for MLIrisFlower.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [ColumnName(@"sepal_length")]
        public float Sepal_length { get; set; }

        [ColumnName(@"sepal_width")]
        public float Sepal_width { get; set; }

        [ColumnName(@"petal_length")]
        public float Petal_length { get; set; }

        [ColumnName(@"petal_width")]
        public float Petal_width { get; set; }

        [ColumnName(@"iris_class")]
        public string Iris_class { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for MLIrisFlower.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName("PredictedLabel")]
        public string Prediction { get; set; }

        public float[] Score { get; set; }
    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("MLIrisFlower.zip");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }

    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }
}
